version: 1.0.0
author: boukew99
name: Jekyll • Simple, blog-aware, static sites
description: Transform your plain text into static websites and blogs
url: https://jekyllrb.com
repository: https://github.com/jekyll/jekyll
timezone: Europe/Amsterdam
favicon: carrot_cake.png
title: Test
twitter:
  username: jekyllrb
logo: "/img/logo-2x.png"

languageCode: "en"

