theme: jekyll-theme-tactile
version: 1.0.0
name: Jekyll • Simple, blog-aware, static sites
description: Transform your plain text into static websites and blogs
url: https://jekyllrb.com
repository: https://github.com/jekyll/jekyll
timezone: America/Los_Angele
title: Test
twitter:
  username: jekyllrb
logo: "/img/logo-2x.png"

languageCode: "en"

