theme: jekyll-theme-tactile
title: Test

languageCode: "en"
params:
  description:          "The most popular HTML, CSS, and JS library in the world."
  authors:              "Mark Otto, Jacob Thornton, and Bootstrap contributors"
  social_image_path:    /docs/5.1/assets/brand/bootstrap-social.png
  social_logo_path:     /docs/5.1/assets/brand/bootstrap-social-logo.png

