theme: jekyll-theme-tactile
title: Test
subtitle: Test2
author: boukew99
description:
email:

twitter_user: test
twitter_tweet_button: true

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"

avatar: "/assets/img/avatar-icon.png"

social-network-links:
  email: "someone@example.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  facebook: deanattali
  github: daattali
  twitter: daattali
  patreon: DeanAttali
  youtube: c/daattali

post_search: true
